### ISSUE TITLE
Al aplicar el parche4 server.js queda con propietario root

### ISSUE THREAD

**Issue by ghost** [llunaplanet/12factor-dojo#2]
Trabajando desde Windows + VirtuaBox + Ubuntu 18.04

**Comment by llunaplanet** [comment]
@lomagi01 Pienso que he solucionado el problema con https://github.com/llunaplanet/12factor-dojo/commit/f009cfc8bc5a2a908a482dcd3dd7e76ed4abaf8a pero no lo puedo probar ahora mismo en el setup que comentas, lo podrías probar?

**Comment by lmartinezg** [comment]
@llunaplanet Aunque ya no utilizo el setup anotado en el issue, lo he probado tanto en ubuntu 18.04 nativo como en dicho setup y funciona correctamente en ambos casos.

Gracias.

**Comment by llunaplanet** [comment]
👍
